# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66077ba681372f389cb929a823a8e718d66d5ef25976215c8d7a553ef47573d56ea42336e10255fd71d11f64fff6ce6970cba742bb09d743535541a9c5fa4743

test:
  secret_key_base: f0c7c46de6436454ce556323387bdf718ea9c0aae20c033835b7dc902341966c58dac98d1282801631f8e7314ba008e03d4b73bdc80c73e4dadb9aa506e82313

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
